### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IMA-G#1]
[Infografía Lenguajes Contratos Inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-IMA-G/files/8654868/Infografia.Lenguajes.Contratos.Inteligentes.pdf)

**Comment by Nayee123** [comment]
Muy buen trabajo 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
